spring:
  datasource:
    url: jdbc:mysql://dbserver/refcheck_db?useSSL=false
    username: refcheck
    password: refcheck
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    # database-platform: org.hibernate.dialect.MySQLDialect